
.pragma library
var screen_width = 800
var screen_height = 480
var status_bar_height = 70
var status_bar_y = 410

var xArray_Constant = [16,211,409,605,16,211,409,605]
var yArray_Constant = [6,6,6,6,190,190,190,190]
var textArray_Constant = ["Audio","Phone","Climate","Settings","Apple Carplay","Android Auto","OnStar Services","Users"]
var focusArray_Constant = ["images/home_audio_active.png","images/home_phone_active.png","images/home_climate_active.png","images/home_settings_active.png","images/home_applecarplay_active.png","images/home_androidauto_active.png","images/home_onstar_active.png","images/home_users_active.png"]
var normalArray_Constant = ["images/home_audio_inactive.png","images/home_phone_inactive.png","images/home_climate_inactive.png","images/home_settings_inactive.png","images/home_applecarplay_inactive.png","images/home_androidauto_inactive.png","images/home_onstar_inactive.png","images/home_users_inactive.png"]
var statusbar_bg = "images/statusbar_bg.png"
var statusbar_separator = "images/statusbar_separator.png"
var home_active = "images/home_active.png"
var home_inactive = "images/home_inactive.png"
var statusbar_timetemp_separator = "images/statusbar_timetemp_separator.png"
var audio_pressed = "images/audio_pressed.png"
var audio_normal = "images/audio_normal.png"
var phone_pressed = "images/phone_pressed.png"
var phone_inactive = "images/phone_inactive.png"
var climate_pressed = "images/climate_pressed.png"
var climate_inactive = "images/climate_inactive.png"
var onstar_pressed = "images/onstar_pressed.png"
var onstar_inactive = "images/onstar_inactive.png"
var source_active = "images/source_active.png"
var sidebar_divider = "images/sidebar_divider.png"
var mymedia_source = "images/mymedia_source.png"
var chevron_inactive = "images/chevron_inactive.png"
var audio_add_device_active = "images/audio_add_device_active.png"
var audio_add_device_inactive = "images/audio_add_device_inactive.png"
var page_indicator_active = "images/page_indicator_active.png"
var bg_main = "images/bg_main.png"
var back_normal = "images/back_normal.png"
var close_normal = "images/close_normal.png"
var separator = "images/statusbar_timetemp_separator.png"
var move_up_active = "images/move_up_active.png"
var move_up_inactive = "images/move_up_inactive.png"
var move_down_active = "images/move_down_active.png"
var move_down_inactive = "images/move_down_inactive.png"
var radio_active = "images/radio_active.png"
var radio_inactive = "images/radio_inactive.png"
var scrollbar_bg_long = "images/scrollbar_bg_long.png"
var settings_button_green_normal = "images/settings_button_green_normal.png"
var delete_normal = "images/delete_normal.png"
var delete_highlight = "images/delete_highlight.png"
var scroll_down_highlight = "images/scroll_down_highlight.png"
var scroll_down_normal = "images/scroll_down_normal.png"
var scroll_up_highlight = "images/scroll_up_highlight.png"
var scroll_up_normal = "images/scroll_up_normal.png"
var toggle_active = "images/toggle_active.png"
var toggle_inactive = "images/toggle_inactive.png"

